package com.web;

import java.io.IOException;
import java.sql.Date;
import javax.servlet.RequestDispatcher;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import com.controller.UserController;
import com.model.User;

@WebServlet("/RegisterServlet")
public class RegisterServlet extends HttpServlet {
    private static final long serialVersionUID = 1L;
    
    public RegisterServlet() {
        super();
    }
    
    @Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
    	
        String action = request.getParameter("action");
        if ("register".equals(action)) {
            String firstname = request.getParameter("firstName");
            String lastname = request.getParameter("lastName");
            String password = request.getParameter("password");
            String customerType = request.getParameter("customertype");
            String dob = request.getParameter("date");
            String email = request.getParameter("email");
            String address = request.getParameter("address");
            String phone = request.getParameter("phoneNumber");
            
            // Create a new user (ID will be auto-generated by the database)
            User u = new User(0, firstname, lastname, password, "Customer", customerType, phone, email, address, Date.valueOf(dob));
            
            UserController uc = new UserController();
            response.setContentType("text/html");
            int flag=uc.addUser(u);
            // Attempt to insert the user; assume insertUser() returns non-zero if successful.
            if (flag!=0) {
                System.out.println("Registration successful.");
                // Set the userId attribute for display purposes.
                request.setAttribute("userId", "Your User ID is "+flag);
                RequestDispatcher rd = request.getRequestDispatcher("register_success.jsp");
                rd.forward(request, response);
            } else {
                request.setAttribute("message", "Registration not successful");
                RequestDispatcher rd = request.getRequestDispatcher("register.jsp");
                rd.forward(request, response);
            }
        }
    }
    
    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        doPost(request, response);
    }
}
